name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "find-yara-x/*"
        omitBody: true
        token: ${{ secrets.GITHUB_TOKEN }}
